/*
 * DPDK L3 Router, Jetson AGX Orin <-> Laptop 1
 *
 * Deliberately minimal. Two subnets only, no default route, no NAT,
 * no internet forwarding. This exists purely to route real traffic
 * generated by the Jetson (ping, iperf3, hping3, scapy, anything)
 * through to Laptop 1 and back, so you can watch it happen cleanly.
 *
 *   Laptop 1 (172.20.10.10/24)          Jetson AGX Orin (192.168.30.10/24)
 *         |                                        |
 *   wired to port 0                          wired to port 1
 *   (PCI 0000:86:00.0)                       (PCI 0000:d8:00.0, or your third NIC)
 *         |                                        |
 *   Port 0 = 172.20.10.1              Port 1 = 192.168.30.1
 *
 * IMPORTANT: DPDK assigns port numbers by ascending PCI address, not by
 * the order of -a flags on the command line. Verify the real mapping the
 * first time you run this by watching the [ARP] Learned lines at startup,
 * they show you exactly which real device address is showing up on which
 * port number. Do not assume, confirm from the live log every time you
 * change which physical port something is wired into.
 *
 * Launch:
 *   sudo ./jetson_router -l 10,11,12 -n 4 --socket-mem=0,512 \
 *       -a 0000:86:00.0 -a 0000:d8:00.0
 */

#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>
#include <signal.h>
#include <string.h>
#include <arpa/inet.h>

#include <rte_eal.h>
#include <rte_ethdev.h>
#include <rte_mbuf.h>
#include <rte_ether.h>
#include <rte_arp.h>
#include <rte_ip.h>
#include <rte_icmp.h>
#include <rte_byteorder.h>
#include <rte_cycles.h>
#include <rte_pdump.h>

#define RX_RING_SIZE 128
#define TX_RING_SIZE 128
#define NUM_MBUFS    8191
#define MBUF_CACHE_SIZE 250
#define BURST_SIZE   32
#define ARP_TABLE_SIZE 32

#define PORT_LAPTOP1 0   /* physical port 0, confirm from live log */
#define PORT_JETSON  1   /* physical port 1, confirm from live log */

/* [ADDED] Per-packet printf() is a syscall -- doing one per packet caps
 * this router at a few thousand pps regardless of how fast DPDK itself
 * could go. Verbose per-packet lines are OFF by default; use the always-on
 * [STATS] summary (see print_stats()) for throughput testing instead.
 * Flip g_verbose to 1 only when debugging connectivity at low/no load. */
static volatile int g_verbose = 0;
#define LOGV(...) do { if (g_verbose) printf(__VA_ARGS__); } while (0)

struct iface_cfg {
    uint16_t port_id;
    uint32_t ip;
    uint32_t netmask;
    uint32_t subnet;
    struct rte_ether_addr mac;
};

struct arp_entry {
    uint32_t ip;
    struct rte_ether_addr mac;
    int valid;
};

static struct iface_cfg ifaces[2];
static struct arp_entry arp_table[2][ARP_TABLE_SIZE];
static struct rte_mempool *mbuf_pool;
static volatile int running = 1;

static void signal_handler(int sig)
{
    if (sig == SIGINT || sig == SIGTERM) {
        printf("\n[INFO] Shutting down...\n");
        running = 0;
    }
}

static uint32_t ip_from_str(const char *s)
{
    struct in_addr a;
    inet_pton(AF_INET, s, &a);
    return rte_be_to_cpu_32(a.s_addr);
}

static void ip_to_str(uint32_t ip, char *buf, size_t len)
{
    snprintf(buf, len, "%u.%u.%u.%u",
              (ip >> 24) & 0xFF, (ip >> 16) & 0xFF, (ip >> 8) & 0xFF, ip & 0xFF);
}

static void mac_to_str(const struct rte_ether_addr *m, char *buf, size_t len)
{
    snprintf(buf, len, "%02X:%02X:%02X:%02X:%02X:%02X",
              m->addr_bytes[0], m->addr_bytes[1], m->addr_bytes[2],
              m->addr_bytes[3], m->addr_bytes[4], m->addr_bytes[5]);
}

static int idx_of(uint16_t port_id)
{
    return (port_id == PORT_LAPTOP1) ? 0 : 1;
}

/* [ADDED] Live throughput stats, printed roughly once a second, driven by
 * rte_eth_stats_get() -- counters the NIC driver maintains itself in
 * hardware/software regardless of what our own code does. This means:
 *   - it costs nothing extra per-packet (no manual counter increments
 *     needed anywhere in the hot path)
 *   - "imissed" specifically tells you packets the NIC dropped because
 *     software couldn't keep up (rx_burst not called often enough / not
 *     fast enough) -- this is your #1 signal for "DPDK itself is the
 *     bottleneck" versus "the bottleneck is upstream/downstream of it"
 * Compare this against what iperf3 reports on the Jetson (sender) and on
 * the Windows laptop (receiver) to localize exactly where loss happens:
 *   Jetson iperf3 send rate  vs  Port1 RX here  ->  loss on the Jetson<->DPDK link
 *   Port1 RX here  vs  Port0 TX here             ->  loss inside the router itself
 *   Port0 TX here  vs  Windows iperf3 recv rate  ->  loss on the DPDK<->Laptop link
 */
static void print_stats(void)
{
    static uint64_t last_cycles;
    static struct rte_eth_stats prev[2];
    static int first_call = 1;

    uint64_t now = rte_get_timer_cycles();
    uint64_t hz  = rte_get_timer_hz();

    if (first_call) {
        first_call = 0;
        last_cycles = now;
        rte_eth_stats_get(PORT_LAPTOP1, &prev[0]);
        rte_eth_stats_get(PORT_JETSON, &prev[1]);
        return;
    }

    double elapsed = (double)(now - last_cycles) / (double)hz;
    if (elapsed < 1.0)
        return;

    struct rte_eth_stats cur[2];
    rte_eth_stats_get(PORT_LAPTOP1, &cur[0]);
    rte_eth_stats_get(PORT_JETSON, &cur[1]);

    static const char *label[2] = { "Laptop1", "Jetson " };

    printf("\n[STATS] ---- %.2fs window ----\n", elapsed);
    for (int i = 0; i < 2; i++) {
        uint64_t rx_pkts  = cur[i].ipackets - prev[i].ipackets;
        uint64_t rx_bytes = cur[i].ibytes   - prev[i].ibytes;
        uint64_t tx_pkts  = cur[i].opackets - prev[i].opackets;
        uint64_t tx_bytes = cur[i].obytes   - prev[i].obytes;
        uint64_t rx_miss  = cur[i].imissed  - prev[i].imissed;   /* dropped by NIC, ring full */
        uint64_t rx_err   = cur[i].ierrors  - prev[i].ierrors;
        uint64_t tx_err   = cur[i].oerrors  - prev[i].oerrors;

        double rx_mbps = (rx_bytes * 8.0) / elapsed / 1e6;
        double tx_mbps = (tx_bytes * 8.0) / elapsed / 1e6;

        printf("  Port %d (%s): RX %8" PRIu64 " pkt/s  %9.2f Mbps | "
               "TX %8" PRIu64 " pkt/s  %9.2f Mbps | rx_miss %" PRIu64
               " rx_err %" PRIu64 " tx_err %" PRIu64 "\n",
               i, label[i],
               (uint64_t)(rx_pkts / elapsed), rx_mbps,
               (uint64_t)(tx_pkts / elapsed), tx_mbps,
               rx_miss, rx_err, tx_err);

        if (rx_miss > 0)
            printf("    ^ Port %d dropped %" PRIu64
                   " incoming packets -- the RX ring filled up because this\n"
                   "      app's poll loop can't drain it fast enough. This IS your bottleneck.\n",
                   i, rx_miss);
    }

    prev[0] = cur[0];
    prev[1] = cur[1];
    last_cycles = now;
}

static void arp_learn(uint16_t port_id, uint32_t ip, const struct rte_ether_addr *mac)
{
    if (ip == 0)
        return;
    int idx = idx_of(port_id);
    struct arp_entry *tbl = arp_table[idx];

    for (int i = 0; i < ARP_TABLE_SIZE; i++) {
        if (tbl[i].valid && tbl[i].ip == ip) {
            tbl[i].mac = *mac;
            return;
        }
    }
    for (int i = 0; i < ARP_TABLE_SIZE; i++) {
        if (!tbl[i].valid) {
            tbl[i].ip = ip;
            tbl[i].mac = *mac;
            tbl[i].valid = 1;
            char ipstr[16];
            ip_to_str(ip, ipstr, sizeof(ipstr));
            LOGV("[ARP] Learned %s on port %u\n", ipstr, port_id);
            return;
        }
    }
}

static int arp_lookup(int idx, uint32_t ip, struct rte_ether_addr *out)
{
    struct arp_entry *tbl = arp_table[idx];
    for (int i = 0; i < ARP_TABLE_SIZE; i++) {
        if (tbl[i].valid && tbl[i].ip == ip) {
            *out = tbl[i].mac;
            return 1;
        }
    }
    return 0;
}

static void send_arp_request(int idx, uint32_t target_ip)
{
    struct rte_mbuf *req = rte_pktmbuf_alloc(mbuf_pool);
    if (req == NULL)
        return;

    struct rte_ether_hdr *eth = rte_pktmbuf_mtod(req, struct rte_ether_hdr *);
    struct rte_arp_hdr *arp = (struct rte_arp_hdr *)(eth + 1);

    rte_ether_addr_copy(&ifaces[idx].mac, &eth->src_addr);
    memset(&eth->dst_addr, 0xFF, RTE_ETHER_ADDR_LEN);
    eth->ether_type = rte_cpu_to_be_16(RTE_ETHER_TYPE_ARP);

    arp->arp_hardware = rte_cpu_to_be_16(RTE_ARP_HRD_ETHER);
    arp->arp_protocol = rte_cpu_to_be_16(RTE_ETHER_TYPE_IPV4);
    arp->arp_hlen = RTE_ETHER_ADDR_LEN;
    arp->arp_plen = sizeof(uint32_t);
    arp->arp_opcode = rte_cpu_to_be_16(RTE_ARP_OP_REQUEST);
    rte_ether_addr_copy(&ifaces[idx].mac, &arp->arp_data.arp_sha);
    arp->arp_data.arp_sip = rte_cpu_to_be_32(ifaces[idx].ip);
    memset(&arp->arp_data.arp_tha, 0, RTE_ETHER_ADDR_LEN);
    arp->arp_data.arp_tip = rte_cpu_to_be_32(target_ip);

    req->pkt_len = req->data_len = sizeof(struct rte_ether_hdr) + sizeof(struct rte_arp_hdr);

    if (rte_eth_tx_burst(ifaces[idx].port_id, 0, &req, 1) == 0)
        rte_pktmbuf_free(req);
}

static void handle_arp(struct rte_mbuf *mbuf, uint16_t in_port)
{
    struct rte_ether_hdr *eth = rte_pktmbuf_mtod(mbuf, struct rte_ether_hdr *);
    struct rte_arp_hdr *arp = (struct rte_arp_hdr *)(eth + 1);
    int idx = idx_of(in_port);

    uint16_t opcode = rte_be_to_cpu_16(arp->arp_opcode);
    uint32_t sender_ip = rte_be_to_cpu_32(arp->arp_data.arp_sip);
    uint32_t target_ip = rte_be_to_cpu_32(arp->arp_data.arp_tip);

    arp_learn(in_port, sender_ip, &arp->arp_data.arp_sha);

    if (opcode != RTE_ARP_OP_REQUEST || target_ip != ifaces[idx].ip) {
        rte_pktmbuf_free(mbuf);
        return;
    }

    rte_ether_addr_copy(&eth->src_addr, &eth->dst_addr);
    rte_ether_addr_copy(&ifaces[idx].mac, &eth->src_addr);
    arp->arp_opcode = rte_cpu_to_be_16(RTE_ARP_OP_REPLY);
    rte_ether_addr_copy(&arp->arp_data.arp_sha, &arp->arp_data.arp_tha);
    arp->arp_data.arp_tip = arp->arp_data.arp_sip;
    rte_ether_addr_copy(&ifaces[idx].mac, &arp->arp_data.arp_sha);
    arp->arp_data.arp_sip = rte_cpu_to_be_32(ifaces[idx].ip);

    if (rte_eth_tx_burst(in_port, 0, &mbuf, 1) == 0)
        rte_pktmbuf_free(mbuf);
    else
        LOGV("[ARP] Replied on port %u: I am %u.%u.%u.%u\n", in_port,
               (ifaces[idx].ip >> 24) & 0xFF, (ifaces[idx].ip >> 16) & 0xFF,
               (ifaces[idx].ip >> 8) & 0xFF, ifaces[idx].ip & 0xFF);
}

static void send_icmp_echo_reply(struct rte_mbuf *mbuf, uint16_t port_id)
{
    struct rte_ether_hdr *eth = rte_pktmbuf_mtod(mbuf, struct rte_ether_hdr *);
    struct rte_ipv4_hdr *ip = (struct rte_ipv4_hdr *)(eth + 1);
    uint8_t ihl = (ip->version_ihl & 0x0F) * 4;
    struct rte_icmp_hdr *icmp = (struct rte_icmp_hdr *)((uint8_t *)ip + ihl);

    struct rte_ether_addr tmp_mac;
    rte_ether_addr_copy(&eth->src_addr, &tmp_mac);
    rte_ether_addr_copy(&eth->dst_addr, &eth->src_addr);
    rte_ether_addr_copy(&tmp_mac, &eth->dst_addr);

    uint32_t tmp_ip = ip->src_addr;
    ip->src_addr = ip->dst_addr;
    ip->dst_addr = tmp_ip;
    ip->time_to_live = 64;
    ip->hdr_checksum = 0;
    ip->hdr_checksum = rte_ipv4_cksum(ip);

    icmp->icmp_type = 0;   /* echo reply */
    icmp->icmp_code = 0;
    icmp->icmp_cksum = 0;
    uint16_t icmp_len = rte_be_to_cpu_16(ip->total_length) - ihl;
    uint32_t cksum = rte_raw_cksum(icmp, icmp_len);
    icmp->icmp_cksum = (uint16_t)~cksum;

    if (rte_eth_tx_burst(port_id, 0, &mbuf, 1) == 0)
        rte_pktmbuf_free(mbuf);
    else
        LOGV("[ICMP] Replied to ping on port %u\n", port_id);
}

static void handle_ipv4(struct rte_mbuf *mbuf, uint16_t in_port)
{
    struct rte_ether_hdr *eth = rte_pktmbuf_mtod(mbuf, struct rte_ether_hdr *);
    struct rte_ipv4_hdr *ip = (struct rte_ipv4_hdr *)(eth + 1);

    uint32_t dst_ip = rte_be_to_cpu_32(ip->dst_addr);
    uint32_t src_ip = rte_be_to_cpu_32(ip->src_addr);

    arp_learn(in_port, src_ip, &eth->src_addr);

    /* Addressed to one of our own two IPs? Answer directly, don't forward. */
    for (int i = 0; i < 2; i++) {
        if (dst_ip == ifaces[i].ip) {
            uint8_t ihl = (ip->version_ihl & 0x0F) * 4;
            if (ip->next_proto_id == IPPROTO_ICMP) {
                struct rte_icmp_hdr *icmp = (struct rte_icmp_hdr *)((uint8_t *)ip + ihl);
                if (icmp->icmp_type == 8) {
                    send_icmp_echo_reply(mbuf, in_port);
                    return;
                }
            }
            rte_pktmbuf_free(mbuf);
            return;
        }
    }

    /* Subnet broadcast? Drop cleanly, never ARP for it. */
    for (int i = 0; i < 2; i++) {
        uint32_t bcast = ifaces[i].subnet | ~ifaces[i].netmask;
        if (dst_ip == bcast) {
            rte_pktmbuf_free(mbuf);
            return;
        }
    }

    /* Route: which of our two known subnets does this belong to? */
    int out_idx = -1;
    for (int i = 0; i < 2; i++) {
        if ((dst_ip & ifaces[i].netmask) == ifaces[i].subnet) {
            out_idx = i;
            break;
        }
    }
    if (out_idx < 0) {
        /* Not Laptop 1, not Jetson. This clean router only knows these
         * two subnets on purpose, drop anything else silently. */
        rte_pktmbuf_free(mbuf);
        return;
    }

    uint16_t out_port = ifaces[out_idx].port_id;
    if (out_port == in_port) {
        rte_pktmbuf_free(mbuf);
        return;
    }

    if (ip->time_to_live <= 1) {
        rte_pktmbuf_free(mbuf);
        return;
    }
    ip->time_to_live--;
    ip->hdr_checksum = 0;
    ip->hdr_checksum = rte_ipv4_cksum(ip);

    struct rte_ether_addr next_hop_mac;
    if (!arp_lookup(out_idx, dst_ip, &next_hop_mac)) {
        send_arp_request(out_idx, dst_ip);
        rte_pktmbuf_free(mbuf);
        return;
    }

    rte_ether_addr_copy(&next_hop_mac, &eth->dst_addr);
    rte_ether_addr_copy(&ifaces[out_idx].mac, &eth->src_addr);

    char sstr[16], dstr[16];
    ip_to_str(src_ip, sstr, sizeof(sstr));
    ip_to_str(dst_ip, dstr, sizeof(dstr));
    const char *proto = ip->next_proto_id == IPPROTO_ICMP ? "ICMP" :
                         ip->next_proto_id == IPPROTO_UDP  ? "UDP"  :
                         ip->next_proto_id == IPPROTO_TCP  ? "TCP"  : "OTHER";

    if (rte_eth_tx_burst(out_port, 0, &mbuf, 1) == 0) {
        rte_pktmbuf_free(mbuf);
    } else {
        LOGV("[ROUTE] %s: %s -> %s | in=port%u out=port%u\n",
               proto, sstr, dstr, in_port, out_port);
    }
}

static void init_port(uint16_t port_id)
{
    struct rte_eth_conf port_conf = {0};

    if (rte_eth_dev_configure(port_id, 1, 1, &port_conf) < 0)
        rte_exit(EXIT_FAILURE, "Cannot configure port %u\n", port_id);
    if (rte_eth_rx_queue_setup(port_id, 0, RX_RING_SIZE,
            rte_eth_dev_socket_id(port_id), NULL, mbuf_pool) < 0)
        rte_exit(EXIT_FAILURE, "RX setup failed on port %u\n", port_id);
    if (rte_eth_tx_queue_setup(port_id, 0, TX_RING_SIZE,
            rte_eth_dev_socket_id(port_id), NULL) < 0)
        rte_exit(EXIT_FAILURE, "TX setup failed on port %u\n", port_id);
    if (rte_eth_dev_start(port_id) < 0)
        rte_exit(EXIT_FAILURE, "Cannot start port %u\n", port_id);
    rte_eth_promiscuous_enable(port_id);
}

static void process_port(uint16_t port_id)
{
    struct rte_mbuf *bufs[BURST_SIZE];
    uint16_t nb_rx = rte_eth_rx_burst(port_id, 0, bufs, BURST_SIZE);

    for (uint16_t i = 0; i < nb_rx; i++) {
        struct rte_ether_hdr *eth = rte_pktmbuf_mtod(bufs[i], struct rte_ether_hdr *);
        uint16_t ether_type = rte_be_to_cpu_16(eth->ether_type);

        if (ether_type == RTE_ETHER_TYPE_ARP)
            handle_arp(bufs[i], port_id);
        else if (ether_type == RTE_ETHER_TYPE_IPV4)
            handle_ipv4(bufs[i], port_id);
        else
            rte_pktmbuf_free(bufs[i]);
    }
}

int main(int argc, char *argv[])
{
    signal(SIGINT, signal_handler);
    signal(SIGTERM, signal_handler);

    int ret = rte_eal_init(argc, argv);
    if (ret < 0)
        rte_exit(EXIT_FAILURE, "Cannot initialize EAL\n");

    uint16_t nb_ports = rte_eth_dev_count_avail();
    if (nb_ports < 2)
        rte_exit(EXIT_FAILURE, "Need at least 2 ports, found %u\n", nb_ports);

    mbuf_pool = rte_pktmbuf_pool_create("MBUF_POOL", NUM_MBUFS * nb_ports,
            MBUF_CACHE_SIZE, 0, RTE_MBUF_DEFAULT_BUF_SIZE, rte_socket_id());
    if (mbuf_pool == NULL)
        rte_exit(EXIT_FAILURE, "Cannot create mbuf pool\n");

    /* [ADDED] rte_pdump_init() starts the multi-process IPC channel that
     * the dpdk-pdump helper tool (and Wireshark, via a FIFO) connects to
     * in order to capture packets straight off these DPDK-bound ports.
     * Without this call, dpdk-pdump has nothing to attach to -- these
     * ports have zero kernel presence, so plain tcpdump/Wireshark can
     * never see them directly. This call is cheap and safe to leave in
     * even when you're not actively capturing. */
    ret = rte_pdump_init();
    if (ret < 0)
        printf("[WARN] rte_pdump_init() failed (%d) -- packet capture via dpdk-pdump won't work\n", ret);

    init_port(PORT_LAPTOP1);
    init_port(PORT_JETSON);

    ifaces[0].port_id = PORT_LAPTOP1;
    ifaces[0].ip = ip_from_str("172.20.10.1");
    ifaces[0].netmask = ip_from_str("255.255.255.0");
    ifaces[0].subnet = ifaces[0].ip & ifaces[0].netmask;
    rte_eth_macaddr_get(PORT_LAPTOP1, &ifaces[0].mac);

    ifaces[1].port_id = PORT_JETSON;
    ifaces[1].ip = ip_from_str("192.168.30.1");
    ifaces[1].netmask = ip_from_str("255.255.255.0");
    ifaces[1].subnet = ifaces[1].ip & ifaces[1].netmask;
    rte_eth_macaddr_get(PORT_JETSON, &ifaces[1].mac);

    char m0[18], m1[18];
    mac_to_str(&ifaces[0].mac, m0, sizeof(m0));
    mac_to_str(&ifaces[1].mac, m1, sizeof(m1));

    printf("============================================================\n");
    printf("  DPDK CLEAN ROUTER: Laptop 1 <-> Jetson AGX Orin\n");
    printf("============================================================\n");
    printf("Port 0 (Laptop 1 side): IP 172.20.10.1  MAC %s\n", m0);
    printf("Port 1 (Jetson side):   IP 192.168.30.1  MAC %s\n", m1);
    printf("============================================================\n");
    printf("[INFO] Watch the ARP Learned lines below to confirm which\n");
    printf("[INFO] real PCI device actually ended up as which port.\n");
    printf("[INFO] Live throughput stats print automatically every ~1s below.\n");
    printf("[INFO] For packet-level capture in Wireshark, in another terminal run e.g.:\n");
    printf("[INFO]   sudo dpdk-pdump -- --pdump 'port=%%u,queue=*,rx-dev=/tmp/port0.pcap'\n");
    printf("[INFO]   (see full instructions in the accompanying writeup)\n");
    printf("[INFO] Press Ctrl+C to stop\n\n");

    while (running) {
        process_port(PORT_LAPTOP1);
        process_port(PORT_JETSON);
        print_stats();
    }

    rte_pdump_uninit();
    printf("\n[INFO] Stopping ports...\n");
    rte_eth_dev_stop(PORT_LAPTOP1);
    rte_eth_dev_stop(PORT_JETSON);
    rte_eth_dev_close(PORT_LAPTOP1);
    rte_eth_dev_close(PORT_JETSON);

    return 0;
}
