/*
 * DPDK L3 Router, Jetson AGX Orin <-> Laptop 1
 *
 * Deliberately minimal. Two subnets only, no default route, no NAT,
 * no internet forwarding. This exists purely to route real traffic
 * generated by the Jetson (ping, iperf3, hping3, scapy, anything)
 * through to Laptop 1 and back, so you can watch it happen cleanly.
 *
 *   DPDK Server, via TAP (192.168.40.2/24)   Jetson AGX Orin (192.168.30.10/24)
 *         |                                        |
 *   wired to port 0                          wired to port 1
 *   (PCI 0000:86:00.0)                       (PCI 0000:d8:00.0, or your third NIC)
 *         |                                        |
 *   Port 0 (TAP) = 192.168.40.1       Port 1 (physical) = 192.168.30.1
 *
 * IMPORTANT: DPDK assigns port numbers by ascending PCI address, not by
 * the order of -a flags on the command line. Verify the real mapping the
 * first time you run this by watching the [ARP] Learned lines at startup,
 * they show you exactly which real device address is showing up on which
 * port number. Do not assume, confirm from the live log every time you
 * change which physical port something is wired into.
 *
 * Launch:
 *   sudo ./jetson_router -l 10,11,12 -n 4 --socket-mem=0,512 \
 *       -a 0000:86:00.0 -a 0000:d8:00.0
 */

#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>
#include <signal.h>
#include <string.h>
#include <arpa/inet.h>

#include <rte_eal.h>
#include <rte_ethdev.h>
#include <rte_mbuf.h>
#include <rte_ether.h>
#include <rte_arp.h>
#include <rte_ip.h>
#include <rte_icmp.h>
#include <rte_byteorder.h>
#include <rte_pdump.h>
#include <rte_cycles.h>

#define RX_RING_SIZE 128
#define TX_RING_SIZE 128
#define NUM_MBUFS    8191
#define MBUF_CACHE_SIZE 250
#define BURST_SIZE   32
#define ARP_TABLE_SIZE 32

#define PORT_GEN 0   /* TAP virtual port, this box's own kernel/iperf3, confirm from live log */
#define PORT_JETSON  1   /* physical port 1, confirm from live log */

struct iface_cfg {
    uint16_t port_id;
    uint32_t ip;
    uint32_t netmask;
    uint32_t subnet;
    struct rte_ether_addr mac;
};

struct arp_entry {
    uint32_t ip;
    struct rte_ether_addr mac;
    int valid;
};

static struct iface_cfg ifaces[2];
static struct arp_entry arp_table[2][ARP_TABLE_SIZE];
static struct rte_mempool *mbuf_pool;
static volatile int running = 1;

/* TX batching, instead of one rte_eth_tx_burst() call per packet, we
 * collect everything destined for a given output port during a single
 * poll cycle and flush it as one real burst call. This is the actual
 * point of DPDK's burst-oriented API, one packet at a time throws away
 * most of the benefit. */
#define TX_PENDING_MAX (BURST_SIZE * 2)
static struct rte_mbuf *tx_pending[2][TX_PENDING_MAX];
static uint16_t tx_pending_count[2];

/* Per-port throughput stats, reset every reporting interval */
static uint64_t rx_pkts[2], rx_bytes[2];
static uint64_t tx_pkts[2], tx_bytes[2];
static uint64_t tx_dropped[2];

/* Built-in packet generator, the DPDK server itself originates traffic
 * out toward the Jetson (port 1), real ICMP echo requests sent through
 * DPDK's own userspace TX path. The Jetson's kernel answers automatically,
 * so we get a genuine round trip with zero extra setup on the Jetson side.
 * This runs alongside normal forwarding in the same process, no need to
 * stop the router to generate traffic anymore. */
static int gen_enabled = 0;
static uint32_t gen_target_ip;
static uint32_t gen_rate_pps = 10;
static uint64_t gen_seq = 0;
static uint64_t gen_sent = 0, gen_replies = 0;

static void enqueue_tx(int out_idx, struct rte_mbuf *mbuf)
{
    if (tx_pending_count[out_idx] >= TX_PENDING_MAX) {
        /* Shouldn't happen given the sizing above, but never silently
         * leak an mbuf if it does */
        rte_pktmbuf_free(mbuf);
        tx_dropped[out_idx]++;
        return;
    }
    tx_pending[out_idx][tx_pending_count[out_idx]++] = mbuf;
}

static void flush_tx(int out_idx)
{
    uint16_t count = tx_pending_count[out_idx];
    if (count == 0)
        return;

    uint16_t sent = rte_eth_tx_burst(ifaces[out_idx].port_id, 0, tx_pending[out_idx], count);

    for (uint16_t i = 0; i < sent; i++)
        tx_bytes[out_idx] += tx_pending[out_idx][i]->pkt_len;
    tx_pkts[out_idx] += sent;

    if (sent < count) {
        tx_dropped[out_idx] += (count - sent);
        for (uint16_t i = sent; i < count; i++)
            rte_pktmbuf_free(tx_pending[out_idx][i]);
    }

    tx_pending_count[out_idx] = 0;
}

static void signal_handler(int sig)
{
    if (sig == SIGINT || sig == SIGTERM) {
        printf("\n[INFO] Shutting down...\n");
        running = 0;
    }
}

static uint32_t ip_from_str(const char *s)
{
    struct in_addr a;
    inet_pton(AF_INET, s, &a);
    return rte_be_to_cpu_32(a.s_addr);
}

static void ip_to_str(uint32_t ip, char *buf, size_t len)
{
    snprintf(buf, len, "%u.%u.%u.%u",
              (ip >> 24) & 0xFF, (ip >> 16) & 0xFF, (ip >> 8) & 0xFF, ip & 0xFF);
}

static void mac_to_str(const struct rte_ether_addr *m, char *buf, size_t len)
{
    snprintf(buf, len, "%02X:%02X:%02X:%02X:%02X:%02X",
              m->addr_bytes[0], m->addr_bytes[1], m->addr_bytes[2],
              m->addr_bytes[3], m->addr_bytes[4], m->addr_bytes[5]);
}

static int idx_of(uint16_t port_id)
{
    return (port_id == PORT_GEN) ? 0 : 1;
}

static void arp_learn(uint16_t port_id, uint32_t ip, const struct rte_ether_addr *mac)
{
    if (ip == 0)
        return;
    int idx = idx_of(port_id);
    struct arp_entry *tbl = arp_table[idx];

    for (int i = 0; i < ARP_TABLE_SIZE; i++) {
        if (tbl[i].valid && tbl[i].ip == ip) {
            tbl[i].mac = *mac;
            return;
        }
    }
    for (int i = 0; i < ARP_TABLE_SIZE; i++) {
        if (!tbl[i].valid) {
            tbl[i].ip = ip;
            tbl[i].mac = *mac;
            tbl[i].valid = 1;
            char ipstr[16];
            ip_to_str(ip, ipstr, sizeof(ipstr));
            printf("[ARP] Learned %s on port %u\n", ipstr, port_id);
            return;
        }
    }
}

static int arp_lookup(int idx, uint32_t ip, struct rte_ether_addr *out)
{
    struct arp_entry *tbl = arp_table[idx];
    for (int i = 0; i < ARP_TABLE_SIZE; i++) {
        if (tbl[i].valid && tbl[i].ip == ip) {
            *out = tbl[i].mac;
            return 1;
        }
    }
    return 0;
}

static void send_arp_request(int idx, uint32_t target_ip)
{
    struct rte_mbuf *req = rte_pktmbuf_alloc(mbuf_pool);
    if (req == NULL)
        return;

    struct rte_ether_hdr *eth = rte_pktmbuf_mtod(req, struct rte_ether_hdr *);
    struct rte_arp_hdr *arp = (struct rte_arp_hdr *)(eth + 1);

    rte_ether_addr_copy(&ifaces[idx].mac, &eth->src_addr);
    memset(&eth->dst_addr, 0xFF, RTE_ETHER_ADDR_LEN);
    eth->ether_type = rte_cpu_to_be_16(RTE_ETHER_TYPE_ARP);

    arp->arp_hardware = rte_cpu_to_be_16(RTE_ARP_HRD_ETHER);
    arp->arp_protocol = rte_cpu_to_be_16(RTE_ETHER_TYPE_IPV4);
    arp->arp_hlen = RTE_ETHER_ADDR_LEN;
    arp->arp_plen = sizeof(uint32_t);
    arp->arp_opcode = rte_cpu_to_be_16(RTE_ARP_OP_REQUEST);
    rte_ether_addr_copy(&ifaces[idx].mac, &arp->arp_data.arp_sha);
    arp->arp_data.arp_sip = rte_cpu_to_be_32(ifaces[idx].ip);
    memset(&arp->arp_data.arp_tha, 0, RTE_ETHER_ADDR_LEN);
    arp->arp_data.arp_tip = rte_cpu_to_be_32(target_ip);

    req->pkt_len = req->data_len = sizeof(struct rte_ether_hdr) + sizeof(struct rte_arp_hdr);

    if (rte_eth_tx_burst(ifaces[idx].port_id, 0, &req, 1) == 0)
        rte_pktmbuf_free(req);
}

static void handle_arp(struct rte_mbuf *mbuf, uint16_t in_port)
{
    struct rte_ether_hdr *eth = rte_pktmbuf_mtod(mbuf, struct rte_ether_hdr *);
    struct rte_arp_hdr *arp = (struct rte_arp_hdr *)(eth + 1);
    int idx = idx_of(in_port);

    uint16_t opcode = rte_be_to_cpu_16(arp->arp_opcode);
    uint32_t sender_ip = rte_be_to_cpu_32(arp->arp_data.arp_sip);
    uint32_t target_ip = rte_be_to_cpu_32(arp->arp_data.arp_tip);

    arp_learn(in_port, sender_ip, &arp->arp_data.arp_sha);

    if (opcode != RTE_ARP_OP_REQUEST || target_ip != ifaces[idx].ip) {
        rte_pktmbuf_free(mbuf);
        return;
    }

    rte_ether_addr_copy(&eth->src_addr, &eth->dst_addr);
    rte_ether_addr_copy(&ifaces[idx].mac, &eth->src_addr);
    arp->arp_opcode = rte_cpu_to_be_16(RTE_ARP_OP_REPLY);
    rte_ether_addr_copy(&arp->arp_data.arp_sha, &arp->arp_data.arp_tha);
    arp->arp_data.arp_tip = arp->arp_data.arp_sip;
    rte_ether_addr_copy(&ifaces[idx].mac, &arp->arp_data.arp_sha);
    arp->arp_data.arp_sip = rte_cpu_to_be_32(ifaces[idx].ip);

    if (rte_eth_tx_burst(in_port, 0, &mbuf, 1) == 0)
        rte_pktmbuf_free(mbuf);
    else
        printf("[ARP] Replied on port %u: I am %u.%u.%u.%u\n", in_port,
               (ifaces[idx].ip >> 24) & 0xFF, (ifaces[idx].ip >> 16) & 0xFF,
               (ifaces[idx].ip >> 8) & 0xFF, ifaces[idx].ip & 0xFF);
}

static void send_icmp_echo_reply(struct rte_mbuf *mbuf, uint16_t port_id)
{
    struct rte_ether_hdr *eth = rte_pktmbuf_mtod(mbuf, struct rte_ether_hdr *);
    struct rte_ipv4_hdr *ip = (struct rte_ipv4_hdr *)(eth + 1);
    uint8_t ihl = (ip->version_ihl & 0x0F) * 4;
    struct rte_icmp_hdr *icmp = (struct rte_icmp_hdr *)((uint8_t *)ip + ihl);

    struct rte_ether_addr tmp_mac;
    rte_ether_addr_copy(&eth->src_addr, &tmp_mac);
    rte_ether_addr_copy(&eth->dst_addr, &eth->src_addr);
    rte_ether_addr_copy(&tmp_mac, &eth->dst_addr);

    uint32_t tmp_ip = ip->src_addr;
    ip->src_addr = ip->dst_addr;
    ip->dst_addr = tmp_ip;
    ip->time_to_live = 64;
    ip->hdr_checksum = 0;
    ip->hdr_checksum = rte_ipv4_cksum(ip);

    icmp->icmp_type = 0;   /* echo reply */
    icmp->icmp_code = 0;
    icmp->icmp_cksum = 0;
    uint16_t icmp_len = rte_be_to_cpu_16(ip->total_length) - ihl;
    uint32_t cksum = rte_raw_cksum(icmp, icmp_len);
    icmp->icmp_cksum = (uint16_t)~cksum;

    if (rte_eth_tx_burst(port_id, 0, &mbuf, 1) == 0)
        rte_pktmbuf_free(mbuf);
    else
        printf("[ICMP] Replied to ping on port %u\n", port_id);
}

/* Generator: build and send a real ICMP echo request FROM this DPDK
 * server, out toward the Jetson, using whichever interface owns that
 * target subnet. Reuses the same ARP table the forwarding path already
 * maintains, if we don't know the Jetson's MAC yet, request it and
 * skip this cycle, same pattern the forwarding path already uses. */
static void generate_ping(int out_idx, uint32_t target_ip)
{
    struct rte_ether_addr next_hop_mac;
    if (!arp_lookup(out_idx, target_ip, &next_hop_mac)) {
        send_arp_request(out_idx, target_ip);
        return;
    }

    struct rte_mbuf *pkt = rte_pktmbuf_alloc(mbuf_pool);
    if (pkt == NULL)
        return;

    const int payload_len = 32;
    size_t total_len = sizeof(struct rte_ether_hdr) + sizeof(struct rte_ipv4_hdr) +
                        sizeof(struct rte_icmp_hdr) + payload_len;

    struct rte_ether_hdr *eth = rte_pktmbuf_mtod(pkt, struct rte_ether_hdr *);
    rte_ether_addr_copy(&ifaces[out_idx].mac, &eth->src_addr);
    rte_ether_addr_copy(&next_hop_mac, &eth->dst_addr);
    eth->ether_type = rte_cpu_to_be_16(RTE_ETHER_TYPE_IPV4);

    struct rte_ipv4_hdr *ip = (struct rte_ipv4_hdr *)(eth + 1);
    memset(ip, 0, sizeof(*ip));
    ip->version_ihl = 0x45;
    ip->total_length = rte_cpu_to_be_16(sizeof(struct rte_ipv4_hdr) +
                                          sizeof(struct rte_icmp_hdr) + payload_len);
    ip->packet_id = rte_cpu_to_be_16((uint16_t)gen_seq);
    ip->time_to_live = 64;
    ip->next_proto_id = IPPROTO_ICMP;
    ip->src_addr = rte_cpu_to_be_32(ifaces[out_idx].ip);
    ip->dst_addr = rte_cpu_to_be_32(target_ip);
    ip->hdr_checksum = 0;
    ip->hdr_checksum = rte_ipv4_cksum(ip);

    struct rte_icmp_hdr *icmp = (struct rte_icmp_hdr *)(ip + 1);
    icmp->icmp_type = 8;   /* echo request */
    icmp->icmp_code = 0;
    icmp->icmp_ident = rte_cpu_to_be_16(0x1234);
    icmp->icmp_seq_nb = rte_cpu_to_be_16((uint16_t)gen_seq);

    uint8_t *payload = (uint8_t *)(icmp + 1);
    for (int i = 0; i < payload_len; i++)
        payload[i] = (uint8_t)i;

    icmp->icmp_cksum = 0;
    uint32_t cksum = rte_raw_cksum(icmp, sizeof(struct rte_icmp_hdr) + payload_len);
    icmp->icmp_cksum = (uint16_t)~cksum;

    pkt->pkt_len = pkt->data_len = total_len;

    if (rte_eth_tx_burst(ifaces[out_idx].port_id, 0, &pkt, 1) == 0) {
        rte_pktmbuf_free(pkt);
    } else {
        gen_sent++;
        gen_seq++;
    }
}

static void handle_ipv4(struct rte_mbuf *mbuf, uint16_t in_port)
{
    struct rte_ether_hdr *eth = rte_pktmbuf_mtod(mbuf, struct rte_ether_hdr *);
    struct rte_ipv4_hdr *ip = (struct rte_ipv4_hdr *)(eth + 1);

    uint32_t dst_ip = rte_be_to_cpu_32(ip->dst_addr);
    uint32_t src_ip = rte_be_to_cpu_32(ip->src_addr);

    arp_learn(in_port, src_ip, &eth->src_addr);

    /* Addressed to one of our own two IPs? Answer directly, don't forward. */
    for (int i = 0; i < 2; i++) {
        if (dst_ip == ifaces[i].ip) {
            uint8_t ihl = (ip->version_ihl & 0x0F) * 4;
            if (ip->next_proto_id == IPPROTO_ICMP) {
                struct rte_icmp_hdr *icmp = (struct rte_icmp_hdr *)((uint8_t *)ip + ihl);
                if (icmp->icmp_type == 8) {
                    send_icmp_echo_reply(mbuf, in_port);
                    return;
                }
                if (icmp->icmp_type == 0) {
                    /* This is a reply to a ping WE generated, count it */
                    gen_replies++;
                    rte_pktmbuf_free(mbuf);
                    return;
                }
            }
            rte_pktmbuf_free(mbuf);
            return;
        }
    }

    /* Subnet broadcast? Drop cleanly, never ARP for it. */
    for (int i = 0; i < 2; i++) {
        uint32_t bcast = ifaces[i].subnet | ~ifaces[i].netmask;
        if (dst_ip == bcast) {
            rte_pktmbuf_free(mbuf);
            return;
        }
    }

    /* Route: which of our two known subnets does this belong to? */
    int out_idx = -1;
    for (int i = 0; i < 2; i++) {
        if ((dst_ip & ifaces[i].netmask) == ifaces[i].subnet) {
            out_idx = i;
            break;
        }
    }
    if (out_idx < 0) {
        /* Not the local generator leg, not Jetson. This clean router only knows these
         * two subnets on purpose, drop anything else silently. */
        rte_pktmbuf_free(mbuf);
        return;
    }

    uint16_t out_port = ifaces[out_idx].port_id;
    if (out_port == in_port) {
        rte_pktmbuf_free(mbuf);
        return;
    }

    if (ip->time_to_live <= 1) {
        rte_pktmbuf_free(mbuf);
        return;
    }
    ip->time_to_live--;
    ip->hdr_checksum = 0;
    ip->hdr_checksum = rte_ipv4_cksum(ip);

    struct rte_ether_addr next_hop_mac;
    if (!arp_lookup(out_idx, dst_ip, &next_hop_mac)) {
        send_arp_request(out_idx, dst_ip);
        rte_pktmbuf_free(mbuf);
        return;
    }

    rte_ether_addr_copy(&next_hop_mac, &eth->dst_addr);
    rte_ether_addr_copy(&ifaces[out_idx].mac, &eth->src_addr);

    enqueue_tx(out_idx, mbuf);
}

static void init_port(uint16_t port_id)
{
    struct rte_eth_conf port_conf = {0};

    if (rte_eth_dev_configure(port_id, 1, 1, &port_conf) < 0)
        rte_exit(EXIT_FAILURE, "Cannot configure port %u\n", port_id);
    if (rte_eth_rx_queue_setup(port_id, 0, RX_RING_SIZE,
            rte_eth_dev_socket_id(port_id), NULL, mbuf_pool) < 0)
        rte_exit(EXIT_FAILURE, "RX setup failed on port %u\n", port_id);
    if (rte_eth_tx_queue_setup(port_id, 0, TX_RING_SIZE,
            rte_eth_dev_socket_id(port_id), NULL) < 0)
        rte_exit(EXIT_FAILURE, "TX setup failed on port %u\n", port_id);
    if (rte_eth_dev_start(port_id) < 0)
        rte_exit(EXIT_FAILURE, "Cannot start port %u\n", port_id);
    rte_eth_promiscuous_enable(port_id);
}

static void process_port(uint16_t port_id)
{
    struct rte_mbuf *bufs[BURST_SIZE];
    uint16_t nb_rx = rte_eth_rx_burst(port_id, 0, bufs, BURST_SIZE);
    int idx = idx_of(port_id);

    rx_pkts[idx] += nb_rx;
    for (uint16_t i = 0; i < nb_rx; i++)
        rx_bytes[idx] += bufs[i]->pkt_len;

    for (uint16_t i = 0; i < nb_rx; i++) {
        struct rte_ether_hdr *eth = rte_pktmbuf_mtod(bufs[i], struct rte_ether_hdr *);
        uint16_t ether_type = rte_be_to_cpu_16(eth->ether_type);

        if (ether_type == RTE_ETHER_TYPE_ARP)
            handle_arp(bufs[i], port_id);
        else if (ether_type == RTE_ETHER_TYPE_IPV4)
            handle_ipv4(bufs[i], port_id);
        else
            rte_pktmbuf_free(bufs[i]);
    }
}

static void print_stats(void)
{
    static const char *names[2] = {"TAP-Gen", "Jetson "};
    printf("\n[STATS] ---- 1.00s window ----\n");
    for (int i = 0; i < 2; i++) {
        double rx_mbps = (rx_bytes[i] * 8.0) / 1e6;
        double tx_mbps = (tx_bytes[i] * 8.0) / 1e6;
        printf("  Port %d (%s): RX %8" PRIu64 " pkt/s %8.2f Mbps | TX %8" PRIu64
               " pkt/s %8.2f Mbps | dropped %" PRIu64 "\n",
               i, names[i], rx_pkts[i], rx_mbps, tx_pkts[i], tx_mbps, tx_dropped[i]);
        rx_pkts[i] = rx_bytes[i] = tx_pkts[i] = tx_bytes[i] = tx_dropped[i] = 0;
    }
}

int main(int argc, char *argv[])
{
    signal(SIGINT, signal_handler);
    signal(SIGTERM, signal_handler);

    int ret = rte_eal_init(argc, argv);
    if (ret < 0)
        rte_exit(EXIT_FAILURE, "Cannot initialize EAL\n");
    argc -= ret;
    argv += ret;

    /* Optional app-level flags, after the DPDK "--" separator:
     *   --gen                enable the built-in generator toward the Jetson
     *   --gen-rate <n>        packets per second, default 10
     * Example:
     *   sudo ./jetson_router -l 10,11,12 -n 4 --socket-mem=0,512 \
     *       -a 0000:86:00.0 -a 0000:d8:00.0 -- --gen --gen-rate 100
     */
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--gen") == 0) {
            gen_enabled = 1;
        } else if (strcmp(argv[i], "--gen-rate") == 0 && i + 1 < argc) {
            gen_rate_pps = (uint32_t)atoi(argv[i + 1]);
            i++;
        }
    }

    /* Enables the external dpdk-pdump tool to attach to this running
     * process and capture real packets off these ports into a pcap file,
     * viewable in Wireshark. This is the only correct way to inspect
     * packet contents on a vfio-pci bound port, since it has no kernel
     * presence for tcpdump to see at all. */
    rte_pdump_init();

    uint16_t nb_ports = rte_eth_dev_count_avail();
    if (nb_ports < 2)
        rte_exit(EXIT_FAILURE, "Need at least 2 ports, found %u\n", nb_ports);

    mbuf_pool = rte_pktmbuf_pool_create("MBUF_POOL", NUM_MBUFS * nb_ports,
            MBUF_CACHE_SIZE, 0, RTE_MBUF_DEFAULT_BUF_SIZE, rte_socket_id());
    if (mbuf_pool == NULL)
        rte_exit(EXIT_FAILURE, "Cannot create mbuf pool\n");

    init_port(PORT_GEN);
    init_port(PORT_JETSON);

    ifaces[0].port_id = PORT_GEN;
    ifaces[0].ip = ip_from_str("192.168.40.1");
    ifaces[0].netmask = ip_from_str("255.255.255.0");
    ifaces[0].subnet = ifaces[0].ip & ifaces[0].netmask;
    rte_eth_macaddr_get(PORT_GEN, &ifaces[0].mac);

    ifaces[1].port_id = PORT_JETSON;
    ifaces[1].ip = ip_from_str("192.168.30.1");
    ifaces[1].netmask = ip_from_str("255.255.255.0");
    ifaces[1].subnet = ifaces[1].ip & ifaces[1].netmask;
    rte_eth_macaddr_get(PORT_JETSON, &ifaces[1].mac);

    gen_target_ip = ip_from_str("192.168.30.10");   /* Jetson's real IP */

    char m0[18], m1[18];
    mac_to_str(&ifaces[0].mac, m0, sizeof(m0));
    mac_to_str(&ifaces[1].mac, m1, sizeof(m1));

    printf("============================================================\n");
    printf("  DPDK CLEAN ROUTER: Local Generator (TAP) <-> Jetson AGX Orin\n");
    printf("============================================================\n");
    printf("Port 0 (TAP, this box):  IP 192.168.40.1  MAC %s\n", m0);
    printf("Port 1 (Jetson side):   IP 192.168.30.1  MAC %s\n", m1);
    printf("============================================================\n");
    if (gen_enabled)
        printf("[GEN] Built-in generator ENABLED, sending toward 192.168.30.10 at %u pkt/s\n", gen_rate_pps);
    printf("[INFO] Watch the ARP Learned lines below to confirm which\n");
    printf("[INFO] real PCI device actually ended up as which port.\n");
    printf("[INFO] Throughput stats print once per second below.\n");
    printf("[INFO] Press Ctrl+C to stop\n");

    uint64_t hz = rte_get_tsc_hz();
    uint64_t last_stats = rte_get_tsc_cycles();
    uint64_t last_gen = last_stats;
    uint64_t gen_interval_cycles = hz / (gen_rate_pps > 0 ? gen_rate_pps : 1);

    while (running) {
        process_port(PORT_GEN);
        process_port(PORT_JETSON);

        flush_tx(0);
        flush_tx(1);

        uint64_t now = rte_get_tsc_cycles();

        if (gen_enabled && (now - last_gen >= gen_interval_cycles)) {
            generate_ping(1 /* PORT_JETSON's iface index */, gen_target_ip);
            last_gen = now;
        }

        if (now - last_stats >= hz) {
            print_stats();
            if (gen_enabled)
                printf("[GEN]  sent=%" PRIu64 "  replies=%" PRIu64 "\n", gen_sent, gen_replies);
            last_stats = now;
        }
    }

    rte_pdump_uninit();
    printf("\n[INFO] Stopping ports...\n");
    rte_eth_dev_stop(PORT_GEN);
    rte_eth_dev_stop(PORT_JETSON);
    rte_eth_dev_close(PORT_GEN);
    rte_eth_dev_close(PORT_JETSON);

    return 0;
}
